#ifndef ELF_ENUMS_H
#define ELF_ENUMS_H

typedef enum {
    ELF_CLASS_32 = 1,
    ELF_CLASS_64 = 2
} ELF_Class_t;

typedef enum {
    ELF_LITTLE_ENDIAN = 1,
    ELF_BIG_ENDIAN = 2
} ELF_Data_t;

typedef enum {
    ELF_ABI_SYSV = 0x00,
    ELF_ABI_HPUX = 0x01,
    ELF_ABI_NETBSD = 0x02,
    ELF_ABI_LINUX = 0x03,
    ELF_ABI_GNUHURD = 0x04,
    ELF_ABI_SOLARIS = 0x06,
    ELF_ABI_AIX = 0x07,
    ELF_ABI_IRIX = 0x08,
    ELF_ABI_FREEBSD = 0x09,
    ELF_ABI_TRU64 = 0x0A,
    ELF_ABI_MODESTO = 0x0B,
    ELF_ABI_OPENBSD = 0x0C,
    ELF_ABI_OPENVMS = 0x0D,
    ELF_ABI_NSK = 0x0E,
    ELF_ABI_AROS = 0x0F,
    ELF_ABI_FENIXOS = 0x10,
    ELF_ABI_CLOUDABI = 0x11,
    ELF_ABI_OPENVOS = 0x12
} ELF_ABI_t;

typedef enum {
    ELF_TYPE_NONE = 0,
    ELF_TYPE_REL = 1,
    ELF_TYPE_EXEC = 2,
    ELF_TYPE_DYN = 3,
    ELF_TYPE_CORE = 4,
    ELF_TYPE_LOOS = 0xFE00,
    ELF_TYPE_HIOS = 0xFEFF,
    ELF_TYPE_LOPROC = 0xFF00,
    ELF_TYPE_HIPROC = 0xFFFF
} ELF_Type_t;

typedef enum {
    ELF_MACHINE_NONE = 0x00,
    ELF_MACHINE_X86 = 0x03,
    ELF_MACHINE_X86_64 = 0x3E,
    ELF_MACHINE_ARM64 = 0xB7,
    ELF_MACHINE_RISCV = 0xF3
} ELF_Machine_t;

typedef enum {
    ELF_SEGMENT_TYPE_NULL = 0x00000000,
    ELF_SEGMENT_TYPE_LOAD = 0x00000001,
    ELF_SEGMENT_TYPE_DYNAMIC = 0x00000002,
    ELF_SEGMENT_TYPE_INTERP = 0x00000003,
    ELF_SEGMENT_TYPE_NOTE = 0x00000004,
    ELF_SEGMENT_TYPE_SHLIB = 0x00000005,
    ELF_SEGMENT_TYPE_PHDR = 0x00000006,
    ELF_SEGMENT_TYPE_TLS = 7,
    ELF_SEGMENT_TYPE_LOOS = 0x60000000,
    ELF_SEGMENT_TYPE_HIOS = 0x6FFFFFFF,
    ELF_SEGMENT_TYPE_LOPROC = 0x70000000,
    ELF_SEGMENT_TYPE_HIPROC = 0x7FFFFFFF
} ELF_Segment_Type_t;

typedef enum {
    ELF_SEGMENT_FLAG_EXECUTABLE = 0x1,
    ELF_SEGMENT_FLAG_WRITABLE = 0x2,
    ELF_SEGMENT_FLAG_READABLE = 0x4
} ELF_Segment_Flag_t;

typedef enum {
    ELF_SECTION_TYPE_NULL = 0x0,
    ELF_SECTION_TYPE_PROGBITS = 0x1,
    ELF_SECTION_TYPE_SYMTAB = 0x2,
    ELF_SECTION_TYPE_STRTAB = 0x3,
    ELF_SECTION_TYPE_RELA = 0x4,
    ELF_SECTION_TYPE_HASH = 0x5,
    ELF_SECTION_TYPE_DYNAMIC = 0x6,
    ELF_SECTION_TYPE_NOTE = 0x7,
    ELF_SECTION_TYPE_NOBITS = 0x8,
    ELF_SECTION_TYPE_REL = 0x9,
    ELF_SECTION_TYPE_SHLIB = 0x0A,
    ELF_SECTION_TYPE_DYNSYM = 0x0B,
    ELF_SECTION_TYPE_INIT_ARRAY = 0x0E,
    ELF_SECTION_TYPE_FINI_ARRAY = 0x0F,
    ELF_SECTION_TYPE_PREINIT_ARRAY = 0x10,
    ELF_SECTION_TYPE_GROUP = 0x11,
    ELF_SECTION_TYPE_SYMTAB_SHNDX = 0x12,
    ELF_SECTION_TYPE_NUM = 0x13,
    ELF_SECTION_TYPE_LOOS = 0x60000000,
    ELF_SECTION_TYPE_HIOS = 0x6FFFFFFF,
    ELF_SECTION_TYPE_LOPROC = 0x70000000,
    ELF_SECTION_TYPE_HIPROC = 0x7FFFFFFF
} ELF_Section_Type_t;

typedef enum {
    ELF_SECTION_FLAG_WRITE = 0x1,
    ELF_SECTION_FLAG_ALLOC = 0x2,
    ELF_SECTION_FLAG_EXECINSTR = 0x4,
    ELF_SECTION_FLAG_MERGE = 0x10,
    ELF_SECTION_FLAG_STRINGS = 0x20,
    ELF_SECTION_FLAG_INFO_LINK = 0x40,
    ELF_SECTION_FLAG_LINK_ORDER = 0x80,
    ELF_SECTION_FLAG_OS_NONCONFORMING = 0x100,
    ELF_SECTION_FLAG_GROUP = 0x200,
    ELF_SECTION_FLAG_TLS = 0x400,
    ELF_SECTION_FLAG_MASKOS = 0x0FF00000,
    ELF_SECTION_FLAG_MASKPROC = 0xF0000000,
    ELF_SECTION_FLAG_ORDERED = 0x4000000,
    ELF_SECTION_FLAG_EXCLUDE = 0x8000000
} ELF_Section_Flag_t;

#endif // ELF_ENUMS_H